### PR TITLE
Issue/13/fix all library references

### PR DESCRIPTION
**Pull request by dholl**
Howdy @cfriedt , Could you give this a try regarding #13 ?  (maybe do a full test build from a clean slate before merging...)

I wrote a scanning script in python, and just call out to otool for the library id's and ref's, and then to install_name_tool for applying changes.  Here, it rewrites the references in each library and executable to use @loader_path with relative references.

Sample usage:
```sh
# Only print warnings or other significant notices where the operator may care:
fix-library-references "${INSTALL_DIR}"

# Print out what the script is changing:
# (This is also silent if there are no changes or warnings/notices...)
fix-library-references -v "${INSTALL_DIR}"

# Also print out a line for every file it encountered that had a library id and/or references.
# (This will always make some noise.)
fix-library-references -v -v "${INSTALL_DIR}"
```

I'm rebuilding from scratch right now to verify everything coherently works together.

### CODE REVIEW

**Comment by dholl** [comment]
The library references seem to work now, so we're getting closer to letting the whole .app bundle be relocatable.  :)

Now it seems we may need to add a few more environment variables to grenv.sh to account for the build ```$APP_DIR``` being baked into other parts of the files, perhaps such as ```$GDK_PIXBUF_MODULEDIR```, ```$GDK_PIXBUF_MODULE_FILE```, and likely others to address troubles such as these warnings and errors below:

(Here, I built the app in $HOME/Applications/GNURadio.app, and afterward, I moved it to $HOME/App to see if it works or not.)

```
zero(ttys000):~> ./App/GNURadio.app/Contents/MacOS/usr/bin/run-grc 

** (process:4929): WARNING **: Trying to register gtype 'GMountMountFlags' as enum when in fact it is of type 'GFlags'

** (process:4929): WARNING **: Trying to register gtype 'GDriveStartFlags' as enum when in fact it is of type 'GFlags'

** (process:4929): WARNING **: Trying to register gtype 'GSocketMsgFlags' as enum when in fact it is of type 'GFlags'
/Users/dholl/App/GNURadio.app/Contents/MacOS/usr/share/gnuradio/python/site-packages/gnuradio/grc/main.py:43: GtkWarning: Cannot open pixbuf loader module file '/Users/dholl/Applications/GNURadio.app/Contents/MacOS/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /Users/dholl/Applications/GNURadio.app/Contents/MacOS/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
to make things work again for the time being.
  gtk.window_set_default_icon(gtk.IconTheme().load_icon('gnuradio-grc', 256, 0))
/Users/dholl/App/GNURadio.app/Contents/MacOS/usr/share/gnuradio/python/site-packages/gnuradio/grc/main.py:43: GtkWarning: Could not find the icon 'gnuradio-grc'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases
  gtk.window_set_default_icon(gtk.IconTheme().load_icon('gnuradio-grc', 256, 0))
Traceback (most recent call last):
  File "/Users/dholl/./App/GNURadio.app/Contents/MacOS/usr/bin/../../usr/bin/gnuradio-companion", line 99, in <module>
    run_main()
  File "/Users/dholl/./App/GNURadio.app/Contents/MacOS/usr/bin/../../usr/bin/gnuradio-companion", line 92, in run_main
    exit(main())
  File "/Users/dholl/App/GNURadio.app/Contents/MacOS/usr/share/gnuradio/python/site-packages/gnuradio/grc/main.py", line 53, in main
    ActionHandler(args, platform)
  File "/Users/dholl/App/GNURadio.app/Contents/MacOS/usr/share/gnuradio/python/site-packages/gnuradio/grc/gui/ActionHandler.py", line 60, in __init__
    self.main_window = MainWindow(platform, self._handle_action)
  File "/Users/dholl/App/GNURadio.app/Contents/MacOS/usr/share/gnuradio/python/site-packages/gnuradio/grc/gui/MainWindow.py", line 80, in __init__
    gen_opts = platform.blocks['options'].get_param('generate_options')
  File "/Users/dholl/App/GNURadio.app/Contents/MacOS/usr/share/gnuradio/python/site-packages/gnuradio/grc/core/utils/odict.py", line 35, in __getitem__
    return self._data[key]
KeyError: 'options'
zsh: exit 1     ./App/GNURadio.app/Contents/MacOS/usr/bin/run-grc
zero(ttys000):~> 
```

**Comment by dholl** [comment]
Ah, hold off on incorporating this PR just yet.  I have a few additions in the works to make ```fix-library-references``` more robust, and a little more flexible --- such as specifying
* ```-L=/path/lib``` to enable automatic library path searches when the script finds references without ```/a/full/path/to/a/file.{dylib,so}```, such as ```libsomething.so``` or ```libanything.dylib``` or ```a/relative/path/libwtf.so```.
* ```-L:=/path1/lib:/path2/lib``` for the same as ```-L=/dir``` but allow a colon-delimited set of directories, such as from an environment variable like ```-L:="${DYLD_LIBRARY_PATH}"```.
* ```-R=/path/lib``` -- adds a library path to the ```@rpath``` search list
* ```-R:=/path1/lib:/path2/lib``` -- adds a colon-delimited set of paths to the ```@rpath``` search list
* ```-E=/path/bin``` -- adds a library path to the ```@executable_path``` search list -- mainly useful for if the script finds ```@executable_path``` within *libraries* instead of executables -- as is sometimes done to library ID strings so that executables pull in this path when they're built.
    * If the script finds ```@executable_path``` in a reference from an executable (that doesn't end in ```.so``` or ```.dylib```, then it knows how to resolve it.  But if it finds ```@executable_path``` on a ```.so``` or ```.dylib```, then it'll search this ```-E...``` set of paths for validation..
* ```-E:=/path1/bin:/path1/sbin:/path2/bin:/path2/sbin``` -- adds a bunch of bin path's to the ```@executable_path``` search list, such as ```-E:="${PATH}"```.

With these -L... and -R... and -E... options, this enables the script to emulate dynamic linker searching, to robustly incorporate all functionality of ```find-broken-dylibs.sh```, and extend it to being able to find and fix broken references that are not ```/fully/qualified/paths/to/libfiles.{dylib,so}```

What do you think?

hmm... Maybe the ```-R...``` specified paths would in addition to whatever rpath's I can extract from ```otool -l "${exe_name}" | grep -A 4 LC_RPATH```

**Comment by cfriedt** [comment]
@dholl - is this good to merge? If not, I'll close this PR and you can make another request later.

**Comment by dholl** [comment]
Yeah, I'll close this for now.  I started to go over-kill by rewriting ```fix-library-references ``` based upon python macholib to gain access to detect RPATH's from executables, since I haven't found a trivial and clean way to read current RPATH settings from binaries.

(The ```otool -l "${exe_name}" | grep -A 4 LC_RPATH ``` shell-jit-su felt like bordering on too much shenanigans, so I figured I'd "go all the way" with macholib for direct Mach-O format reading/writing from python, especially once I noticed that macholib comes standard on OS X...)

**Comment by cfriedt** [comment]
I actually thought it would be better to write a tool to fix library references in C++ and just borrow some source code from Apple for it, because running it in the shell is _really_ slow.

**Pull request closed without merging**
